### Request 1
POST  http://localhost:3000/api/products
Content-Type: application/json


{
  "title": "pizza7",
  "img": "/images/pizza.png",
  "desc": "desc7",
  "prices": [17,19,21],
  "extraOptions": [{"text": "Spicy sauce", "price": 2}, {"text": "Garlic sauce", "price": 3}] 
}